/*
 * AlgorithmDescriptionDialog.java
 *
 * Created on March 16, 2008, 9:18 PM
 */

package com.megaware.multipleencrypter.frames;

import com.megaware.multipleencrypter.objects.AlgorithmObject;

/**
 *
 * @author  sandeep
 */
public class AlgorithmDescriptionDialog extends javax.swing.JDialog {
    
    /** Creates new form AlgorithmDescriptionDialog */
    public AlgorithmDescriptionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblAlgDescription = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAlgName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        lblModifiedDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Algorithm Description");
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.Color.orange);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DESCRIPTION ABOUT THE SELECTED ALGORITHM");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 670, 50);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Description of Algorithm"));
        jPanel2.setLayout(null);

        lblAlgDescription.setBackground(java.awt.Color.white);
        lblAlgDescription.setOpaque(true);
        jScrollPane1.setViewportView(lblAlgDescription);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 640, 200);

        jLabel2.setText("Name:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 40, 130, 17);

        lblAlgName.setBackground(new java.awt.Color(255, 255, 255));
        lblAlgName.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblAlgName.setOpaque(true);
        jPanel2.add(lblAlgName);
        lblAlgName.setBounds(160, 40, 490, 20);

        jLabel3.setText("Description of the alogrithm");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 160, 180, 17);

        jLabel4.setText("Author");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 70, 43, 17);

        jLabel5.setText("version");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 100, 80, 17);

        jLabel6.setText("Modified Date");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 130, 100, 17);

        lblAuthor.setBackground(java.awt.Color.white);
        lblAuthor.setOpaque(true);
        jPanel2.add(lblAuthor);
        lblAuthor.setBounds(160, 70, 450, 20);

        lblVersion.setBackground(java.awt.Color.white);
        lblVersion.setOpaque(true);
        jPanel2.add(lblVersion);
        lblVersion.setBounds(160, 100, 460, 20);

        lblModifiedDate.setBackground(java.awt.Color.white);
        lblModifiedDate.setOpaque(true);
        jPanel2.add(lblModifiedDate);
        lblModifiedDate.setBounds(160, 130, 460, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 60, 660, 390);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(null);

        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel3.add(btnClose);
        btnClose.setBounds(290, 5, 130, 29);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 460, 660, 40);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-698)/2, (screenSize.height-536)/2, 698, 536);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlgorithmDescriptionDialog dialog = new AlgorithmDescriptionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // function to set the details of the algorithm using the passed
    // AlgorithmObject
    public void setDetails(AlgorithmObject object) {
        lblAlgName.setText(object.getAlgname());
        lblAlgDescription.setText(object.getDescription());
        lblAuthor.setText(object.getAuthor());
        lblModifiedDate.setText(object.getDatemodified().toString());
        lblVersion.setText(object.getVersion());
        setTitle("Algorithm  Description [ "+object.getAlgname()+" ]");
        setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlgDescription;
    private javax.swing.JLabel lblAlgName;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblModifiedDate;
    private javax.swing.JLabel lblVersion;
    // End of variables declaration//GEN-END:variables
    
}
