/*
 * ProgramDetailsDialog.java
 *
 * Created on April 23, 2008, 3:27 PM
 */

package com.megaware.multipleencrypter.frames;

import com.megaware.multipleencrypter.methods.GeneralMethods;
import com.megaware.multipleencrypter.methods.SingleEncryptionAlgorithmMethods;
import com.megaware.multipleencrypter.objects.AlgorithmObject;
import java.io.File;

/**
 *
 * @author  sandeep
 */
public class ProgramDetailsDialog extends javax.swing.JDialog {
    
    /** Creates new form ProgramDetailsDialog */
    public ProgramDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        readAndSetAllData();
    }

    void setCurrTab(int i) {        
        tabDetails.setSelectedIndex(i);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tabDetails = new javax.swing.JTabbedPane();
        pnlAbout = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lblAboutDetails = new javax.swing.JLabel();
        pnlCredits = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblCredits = new javax.swing.JLabel();
        pnlDonations = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblDonations = new javax.swing.JLabel();
        pnlLicense = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblLicense = new javax.swing.JLabel();
        pnlAlgorithms = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lblAlgorithms = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jPanel3.add(btnOk);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DETAILS OF ENCRYPTER PROGRAM");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        pnlAbout.setLayout(new java.awt.BorderLayout());

        lblAboutDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane5.setViewportView(lblAboutDetails);

        pnlAbout.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        tabDetails.addTab("About program", pnlAbout);

        pnlCredits.setLayout(new java.awt.BorderLayout());

        lblCredits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane1.setViewportView(lblCredits);

        pnlCredits.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabDetails.addTab("Credits", pnlCredits);

        pnlDonations.setLayout(new java.awt.BorderLayout());

        lblDonations.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane2.setViewportView(lblDonations);

        pnlDonations.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        tabDetails.addTab("Donations", pnlDonations);

        pnlLicense.setLayout(new java.awt.BorderLayout());

        lblLicense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane3.setViewportView(lblLicense);

        pnlLicense.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tabDetails.addTab("License", pnlLicense);

        pnlAlgorithms.setLayout(new java.awt.BorderLayout());

        lblAlgorithms.setBackground(java.awt.Color.white);
        lblAlgorithms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlgorithms.setOpaque(true);
        jScrollPane4.setViewportView(lblAlgorithms);

        pnlAlgorithms.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        tabDetails.addTab("Algorithms", pnlAlgorithms);

        jPanel2.add(tabDetails, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-607)/2, (screenSize.height-622)/2, 607, 622);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProgramDetailsDialog dialog = new ProgramDetailsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // function to read and set all file data
    protected void readAndSetAllData() {
        readAboutPanelData();
        readCreditData();
        readDonationsData();
        readAlgorithmsData();
        readLicenseContent();
    }
    
    //function to read the about data 
    protected void readAboutPanelData() {
        String content=new GeneralMethods().readFileContent(new File(new GeneralMethods().getApplicationPath()+"settings/aboutprogram.html"));
        if(content==null) {
            content="File not found (aboutprogram.html) in settings folder";            
        }
        lblAboutDetails.setText(content);
    }
    
    // function to read the credits data
    protected void readCreditData() {
        String content=new GeneralMethods().readFileContent(new File(new GeneralMethods().getApplicationPath()+"settings/credits.html"));
        if(content==null) {
            content="File not found (credit.html) in settings folder";            
        }
        lblCredits.setText(content);
    }
    
    // function to read the donations data
    protected void readDonationsData() {
        String content=new GeneralMethods().readFileContent(new File(new GeneralMethods().getApplicationPath()+"settings/donations.html"));
        if(content==null) {
            content="File not found (donations.html) in settings folder";            
        }
        lblDonations.setText(content);
    }
    
    // FUNCTION TO create and read the algorithms
    protected void readAlgorithmsData() {
        java.io.File file=new java.io.File(new GeneralMethods().getApplicationPath()+"algorithms");
        String files[]=file.list();
        int index=1;
        String msg="<html>";        
        for (int i = 0; i < files.length; i++) {            
            if(files[i].endsWith("ALG")) {
                AlgorithmObject obj=new SingleEncryptionAlgorithmMethods().readAlgorithmObject(
                        new GeneralMethods().getApplicationPath()+"algorithms/"+files[i]);
                msg+="<font color =blue size=4><u>"+" Algorithm "+Integer.toString(index)+"</u></font><br><br>"+
                        "Name  ----------> "+obj.getAlgname()+"<br>"+
                        "Author ---------> "+obj.getAuthor()+"<br>"+
                        "Date Modified --> "+obj.getDatemodified().toString()+"<br>"+
                        "Version -------->"+obj.getVersion()+"<br>"+
                        "Description ----> <br>"+obj.getDescription()+"<br><br><br>";
                index++;
            }
        }
        if(msg.equals("<html>")) {
            msg="Algorithms not found";
        }        
        lblAlgorithms.setText(msg);
    }
    
    // function to read the license file
    protected void readLicenseContent() {
        String content=new GeneralMethods().readFileContent(new File(new GeneralMethods().getApplicationPath()+"settings/license.html"));
        if(content==null) {
            content="File not found (license.html) in settings folder";            
        }
        lblLicense.setText(content);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblAboutDetails;
    private javax.swing.JLabel lblAlgorithms;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblDonations;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JPanel pnlAbout;
    private javax.swing.JPanel pnlAlgorithms;
    private javax.swing.JPanel pnlCredits;
    private javax.swing.JPanel pnlDonations;
    private javax.swing.JPanel pnlLicense;
    private javax.swing.JTabbedPane tabDetails;
    // End of variables declaration//GEN-END:variables
    
}
